name: Analyze

on: push

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Retrieve the secret and decode it to a file
        env:
          FIREBASE_OPTIONS_BASE64: ${{ secrets.FIREBASE_OPTIONS_BASE64 }}
          GOOGLE_SERVICES_JSON_ANDROID_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_ANDROID_BASE64 }}
          GOOGLE_SERVICE_INFO_PLIST_IOS_BASE64: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST_IOS_BASE64 }}
          GOOGLE_SERVICE_INFO_PLIST_MACOS_BASE64: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST_MACOS_BASE64 }}
          FIREBASE_JSON_BASE64: ${{ secrets.FIREBASE_JSON_BASE64 }}
          KEY_PROPERTIES_BASE64: ${{ secrets.KEY_PROPERTIES_BASE64 }}
          RELEASE_JKS_BASE64: ${{ secrets.RELEASE_JKS_BASE64 }}

        run: |
          echo $FIREBASE_OPTIONS_BASE64 | base64 -di > lib/firebase_options.dart
          echo $GOOGLE_SERVICES_JSON_ANDROID_BASE64 | base64 -di > android/app/google-services.json
          echo $GOOGLE_SERVICE_INFO_PLIST_IOS_BASE64 | base64 --decode > ios/Runner/GoogleService-Info.plist
          echo $GOOGLE_SERVICE_INFO_PLIST_MACOS_BASE64 | base64 --decode > macos/Runner/GoogleService-Info.plist
          echo $FIREBASE_JSON_BASE64 | base64 --decode > firebase.json
          echo $KEY_PROPERTIES_BASE64 | base64 --decode > android/key.properties     
          echo $RELEASE_JKS_BASE64 | base64 --decode > android/app/release.jks     

      - name: Install dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Lint test
        run: |
          dart format . --set-exit-if-changed
          dart analyze --fatal-infos
