name: reevie
description: "Movie APP by Virexa Technologies"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # UI
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # Annotations
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Navigation
  go_router: ^15.1.3

  # Database
  firebase_core: ^3.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.6.5

  # Code Generator
  build_runner: ^2.4.15

  # Builder
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  go_router_builder: ^2.9.0

flutter:
  uses-material-design: true
  generate: true
